Importing the Dependencies

In [8]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [9]:
df = pd.read_csv('insurance.csv')
df.head()

,Id,age,gender,bmi,bloodpressure,diabetic,children,smoker,region,claim
0,1,39.0,male,23.2,91,Yes,0,No,southeast,1121.87
1,2,24.0,male,30.1,87,No,0,No,southeast,1131.51
2,3,NaN,male,33.3,82,Yes,0,No,southeast,1135.94
3,4,NaN,male,33.7,80,No,0,No,northwest,1136.40
4,5,NaN,male,34.1,100,No,0,No,northwest,1137.01

Data Cleaning

In [10]:
df.shape

(1340, 10)

In [11]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1340 entries, 0 to 1339
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             1340 non-null   int64
 1   age            1335 non-null   float64
 2   gender         1340 non-null   str
 3   bmi            1340 non-null   float64
 4   bloodpressure  1340 non-null   int64
 5   diabetic       1340 non-null   str
 6   children       1340 non-null   int64
 7   smoker         1340 non-null   str
 8   region         1337 non-null   str
 9   claim          1340 non-null   float64
dtypes: float64(3), int64(3), str(4)
memory usage: 104.8 KB

In [13]:
pd.set_option('display.float_format', '{:.2f}'.format)
sns.set(style = 'whitegrid', palette = 'Set2', font_scale = 1.1)
df.head()

,Id,age,gender,bmi,bloodpressure,diabetic,children,smoker,region,claim
0,1,39.00,male,23.20,91,Yes,0,No,southeast,1121.87
1,2,24.00,male,30.10,87,No,0,No,southeast,1131.51
2,3,NaN,male,33.30,82,Yes,0,No,southeast,1135.94
3,4,NaN,male,33.70,80,No,0,No,northwest,1136.40
4,5,NaN,male,34.10,100,No,0,No,northwest,1137.01

In [15]:
df.duplicated().sum()

np.int64(0)

In [16]:
df.isnull().sum()

Id               0
age              5
gender           0
bmi              0
bloodpressure    0
diabetic         0
children         0
smoker           0
region           3
claim            0
dtype: int64

In [18]:
df.dropna(inplace = True) # as there are very few null values, we can drop them without losing much data
df.shape

(1332, 10)

In [20]:
df.describe()

           Id     age     bmi  bloodpressure  children    claim
count 1332.00 1332.00 1332.00        1332.00   1332.00  1332.00
mean   674.47   38.09   30.66          94.19      1.10 13325.25
std    384.70   11.11    6.12          11.45      1.21 12109.62
min      1.00   18.00   16.00          80.00      0.00  1121.87
25%    341.75   29.00   26.20          86.00      0.00  4760.16
50%    674.50   38.00   30.35          92.00      1.00  9412.97
75%   1007.25   47.00   34.73          99.00      2.00 16781.33
max   1340.00   60.00   53.10         140.00      5.00 63770.43